export interface Params {
	/** Private token, usually generated by login/token.php */
	privatetoken: string | null;
}

/**
 * warning
 */
export interface ReturnsWarningsItem {
	/** item */
	item: string | null;
	/** item id */
	itemid: number | null;
	/** the warning code can be used by the client app to implement specific behaviour */
	warningcode: string | null;
	/** untranslated english message to explain the warning */
	message: string | null;
}

/**
 * list of warnings
 */
export type ReturnsWarnings = ReturnsWarningsItem[];

export interface Returns {
	/** Auto-login key for a single usage with time expiration. */
	key: string | null;
	/** Auto-login URL. */
	autologinurl: string | null;
	/** list of warnings */
	warnings: ReturnsWarnings;
}
