export interface Params {
	/** The context ID */
	contextid: number | null;
	/** The prompt text for the AI service */
	prompttext: string | null;
	/** The aspect ratio of the image */
	aspectratio: string | null;
	/** The quality of the image */
	quality: string | null;
	/** The number of images to generate */
	numimages?: number | null;
	/** The style of the image */
	style?: string | null;
}

export interface Returns {
	/** Was the request successful */
	success: boolean | null;
	/** Revised prompt generated by the AI */
	revisedprompt?: string | null;
	/** Draft file URL for the image */
	drafturl?: string | null;
	/** Error code if any */
	errorcode?: number | null;
	/** Error message if any */
	error?: string | null;
}
